version: '3.8'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./server
    expose:
      - "5000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: 
      sh -c "pipenv run python src/manage.py makemigrations &&
             pipenv run python src/manage.py migrate &&
             pipenv run python src/manage.py runserver 0.0.0.0:5000"

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - app
